spring.application.name=avis-jeux-video

# H2
spring.datasource.url=jdbc:h2:mem:avisdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# JPA
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.show-sql=false
spring.jpa.defer-datasource-initialization=true
spring.sql.init.mode=never

# JWT
security.jwt.secret=change-me-super-secret-key-esgi-2026-minimum-32-chars
security.jwt.expiration-hours=24

# Thymeleaf
spring.thymeleaf.cache=false
spring.thymeleaf.encoding=UTF-8
# Springdoc / Swagger
springdoc.swagger-ui.enabled=true
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.api-docs.enabled=true
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.try-it-out-enabled=true
# Comptes de test (dev uniquement)
app.init.joueur.email=nouhaila@example.com
app.init.joueur.pseudo=Nouhaila
app.init.joueur.password=password
app.init.moderateur.email=ilias@example.com
app.init.moderateur.pseudo=Ilias
app.init.moderateur.telephone=0612345678
app.init.moderateur.password=password
